//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma_CPFOriginal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntregaActividades
    {
        public int idEntregaActividad { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public string descripcionEntrega { get; set; }
        public string valor_Obtenido { get; set; }
        public int idActividad { get; set; }
        public int idAlumno { get; set; }
    
        public virtual Actividades Actividades { get; set; }
        public virtual Alumnos Alumnos { get; set; }
    }
}
