//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma_CPFOriginal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreguntasExamen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreguntasExamen()
        {
            this.RespuestasAlumno = new HashSet<RespuestasAlumno>();
        }
    
        public int idPregunta { get; set; }
        public int idExamen { get; set; }
        public string enunciadoPregunta { get; set; }
        public string tipoPregunta { get; set; }
        public string resp1 { get; set; }
        public string resp2 { get; set; }
        public string resp3 { get; set; }
        public string resp4 { get; set; }
        public string solucion { get; set; }
        public string valorpuntos { get; set; }
    
        public virtual Examenes Examenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestasAlumno> RespuestasAlumno { get; set; }
    }
}
