//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma_CPFOriginal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespuestasAlumno
    {
        public int idRespuestaAlumno { get; set; }
        public int idPregunta { get; set; }
        public int idExamen { get; set; }
        public int idAlumno { get; set; }
        public string respuesta { get; set; }
        public Nullable<int> puntosRespuesta { get; set; }
    
        public virtual Alumnos Alumnos { get; set; }
        public virtual Examenes Examenes { get; set; }
        public virtual PreguntasExamen PreguntasExamen { get; set; }
    }
}
