//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma_CPFOriginal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tareas()
        {
            this.EntregasTareas = new HashSet<EntregasTareas>();
        }
    
        public int idTarea { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_I { get; set; }
        public System.DateTime fecha_E { get; set; }
        public string descripcion { get; set; }
        public string tipoTarea { get; set; }
        public int idMateria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntregasTareas> EntregasTareas { get; set; }
        public virtual Materias Materias { get; set; }
    }
}
